server:
  port: 8888
  
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    password: 
    username: sa
    driver-class-name: org.h2.Driver     

myapp:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/testapp?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    maxPoolSize: 30
      
jwt:
  security:
    key: ishanitech
  applicationName: ishanitech
  expirationDate: 360000
  auth:
    header: Authorization
    schema: Bearer 
